### ISSUE TITLE
Mismatch of roles after update

### ISSUE THREAD

**Issue by tmberthold** [sovity/authority-portal#104] opened 2024-03-15 14:10 UTC
### Description - What happened? *

We observed a inconsistency when the admin changes a users role. The role-definitions do not get updated in all relevant areas at the same time (see screenshot). I can understand, that it may be needed to log in again to finalize the change of a a users role. However on this I would prefer the process of the last version, where a user got automatically logged out when his role was changed as this did not lead to inconsistencies.

### Expected Behavior *

/

### Observed Behavior *

/

**Comment by kamilczaja** [comment] 2024-03-19 08:06
Duplicate of #111

**Closed by kamilczaja** 2024-03-19 08:06 UTC
Labels: kind/bug, area/frontend, area/backend
