### ISSUE TITLE
Register organisation: dropdown icon present on fields without dropdown

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#25] opened 2024-03-11 12:53 UTC
### Description - What happened? *

-

### Expected Behavior *

If there are multiple options for the job list (or other field) should display the icon otherwise dropdown icon is not required.

### Observed Behavior *

Dropdown icon is displayed in many of the fields in the Organization register page without having an actual dropdown.

### Steps to Reproduce

1. Launch the application as Authority admin
2. Click on My Organization > Users and Roles > Click on Invite User > Enter First Name, Last Name, Email and select Role > Click on send Invitation
3. Click on the link received in an email and set the password with QR scan and enter OTP > Login with this user > Place cursor on Job Title

### Screenshots

![Screenshot-2024-03-10-at-13 08 10](https://github.com/sovity/authority-portal/assets/36418748/f587e4de-4dac-4179-b29b-31cd13a1c0e9)
![Screenshot-2024-03-10-at-13 08 51](https://github.com/sovity/authority-portal/assets/36418748/eb984ee1-e35b-4265-9ffe-a7ddda0b8ffd)

**Comment by kamilczaja** [comment] 2024-03-11 15:08
The icon shown in the screenshots is the native macOS autofill feature, not a drop-down.
Closing as the form works as intended.

**Closed by kamilczaja** 2024-03-11 15:08 UTC
Labels: kind/bug, area/frontend
