### ISSUE TITLE
Odd behaviour when copying connector URL

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#53] opened 2024-03-12 13:40 UTC
### Description - What happened? *

When copying the connector Endpoint or the Management API URL the UI changes.

### Expected Behavior *

/

### Observed Behavior *

/

### Steps to Reproduce

1. Go to {my Org} > Connectors
2. Open a connectors detail page
3. Click on one of the copy Icons
4. After clicking on of the copy Icons the UI changes

### Screenshots

<img width="290" alt="UI_before_Click" src="https://github.com/sovity/authority-portal/assets/36418748/c349375f-7c17-4810-ab96-1743cff8edc7">
<img width="281" alt="UI_after_Click" src="https://github.com/sovity/authority-portal/assets/36418748/7227c383-d3a9-4c86-86ef-d46707cee351">

**Comment by illfixit** [comment] 2024-03-13 09:52
can't reproduce the issue. I thougth the problem could be because of longer url but still looks fine on windows chrome and firefox

**Comment by jkbquabeck** [comment] 2024-03-15 10:10
I'll request more specifics.

**Comment by jkbquabeck** [comment] 2024-03-15 10:46
Ticket was closed in Fautmanagement System.
Closed as no longer reproducible.

**Closed by jkbquabeck** 2024-03-15 10:46 UTC
Labels: kind/bug, status/updated, area/frontend, status/not-reproducible
