### ISSUE TITLE
Precise error message needed

### ISSUE THREAD

**Issue by jridderbusch** [sovity/authority-portal#114] opened 2024-03-18 08:28 UTC
### Description - What happened? *

Here is how the error happened:

1. I tried to register as organisation in the MDS Portal

2. My organisation was rejected but not deleted.

3. I tried again to register as organisation. When I clicked on the "register" button, there was an error message "Failed registration".

The error is fine. But the message should be preciser, for example "Your email address already exists in the system." or whatever the true reason is. This improves the user's experience and also helps us in problem shooting.

### Expected Behavior *

/

### Observed Behavior *

/

**Comment by kamilczaja** [comment] 2024-03-19 08:10
Duplicate of #106

**Closed by kamilczaja** 2024-03-19 08:10 UTC
Labels: kind/bug, area/frontend, area/backend
